// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(portkiller_ffiFFI)
import portkiller_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_portkiller_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_portkiller_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol RustEngineProtocol : AnyObject {
    
    func addFavorite(port: UInt16) throws 
    
    func addWatchedPort(port: UInt16, notifyOnStart: Bool, notifyOnStop: Bool) throws  -> RustWatchedPort
    
    func getFavorites()  -> [UInt16]
    
    func getPendingNotifications()  -> [RustNotification]
    
    func getPorts()  -> [RustPortInfo]
    
    func getWatchedPorts()  -> [RustWatchedPort]
    
    func hasPendingNotifications()  -> Bool
    
    func isFavorite(port: UInt16)  -> Bool
    
    func isPortActive(port: UInt16)  -> Bool
    
    func isProcessRunning(pid: UInt32)  -> Bool
    
    func isWatched(port: UInt16)  -> Bool
    
    func killPort(port: UInt16) throws  -> Bool
    
    func killProcess(pid: UInt32, force: Bool) throws  -> Bool
    
    func refresh() throws 
    
    func reloadConfig() throws 
    
    func removeFavorite(port: UInt16) throws 
    
    func removeWatchedPort(port: UInt16) throws 
    
    func toggleFavorite(port: UInt16) throws  -> Bool
    
    func toggleWatch(port: UInt16) throws  -> Bool
    
    func updateWatchedPort(port: UInt16, notifyOnStart: Bool, notifyOnStop: Bool) throws 
    
}

open class RustEngine:
    RustEngineProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_portkiller_ffi_fn_clone_rustengine(self.pointer, $0) }
    }
public convenience init()throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeRustEngineError.lift) {
    uniffi_portkiller_ffi_fn_constructor_rustengine_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_portkiller_ffi_fn_free_rustengine(pointer, $0) }
    }

    

    
open func addFavorite(port: UInt16)throws  {try rustCallWithError(FfiConverterTypeRustEngineError.lift) {
    uniffi_portkiller_ffi_fn_method_rustengine_add_favorite(self.uniffiClonePointer(),
        FfiConverterUInt16.lower(port),$0
    )
}
}
    
open func addWatchedPort(port: UInt16, notifyOnStart: Bool, notifyOnStop: Bool)throws  -> RustWatchedPort {
    return try  FfiConverterTypeRustWatchedPort.lift(try rustCallWithError(FfiConverterTypeRustEngineError.lift) {
    uniffi_portkiller_ffi_fn_method_rustengine_add_watched_port(self.uniffiClonePointer(),
        FfiConverterUInt16.lower(port),
        FfiConverterBool.lower(notifyOnStart),
        FfiConverterBool.lower(notifyOnStop),$0
    )
})
}
    
open func getFavorites() -> [UInt16] {
    return try!  FfiConverterSequenceUInt16.lift(try! rustCall() {
    uniffi_portkiller_ffi_fn_method_rustengine_get_favorites(self.uniffiClonePointer(),$0
    )
})
}
    
open func getPendingNotifications() -> [RustNotification] {
    return try!  FfiConverterSequenceTypeRustNotification.lift(try! rustCall() {
    uniffi_portkiller_ffi_fn_method_rustengine_get_pending_notifications(self.uniffiClonePointer(),$0
    )
})
}
    
open func getPorts() -> [RustPortInfo] {
    return try!  FfiConverterSequenceTypeRustPortInfo.lift(try! rustCall() {
    uniffi_portkiller_ffi_fn_method_rustengine_get_ports(self.uniffiClonePointer(),$0
    )
})
}
    
open func getWatchedPorts() -> [RustWatchedPort] {
    return try!  FfiConverterSequenceTypeRustWatchedPort.lift(try! rustCall() {
    uniffi_portkiller_ffi_fn_method_rustengine_get_watched_ports(self.uniffiClonePointer(),$0
    )
})
}
    
open func hasPendingNotifications() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_portkiller_ffi_fn_method_rustengine_has_pending_notifications(self.uniffiClonePointer(),$0
    )
})
}
    
open func isFavorite(port: UInt16) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_portkiller_ffi_fn_method_rustengine_is_favorite(self.uniffiClonePointer(),
        FfiConverterUInt16.lower(port),$0
    )
})
}
    
open func isPortActive(port: UInt16) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_portkiller_ffi_fn_method_rustengine_is_port_active(self.uniffiClonePointer(),
        FfiConverterUInt16.lower(port),$0
    )
})
}
    
open func isProcessRunning(pid: UInt32) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_portkiller_ffi_fn_method_rustengine_is_process_running(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(pid),$0
    )
})
}
    
open func isWatched(port: UInt16) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_portkiller_ffi_fn_method_rustengine_is_watched(self.uniffiClonePointer(),
        FfiConverterUInt16.lower(port),$0
    )
})
}
    
open func killPort(port: UInt16)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeRustEngineError.lift) {
    uniffi_portkiller_ffi_fn_method_rustengine_kill_port(self.uniffiClonePointer(),
        FfiConverterUInt16.lower(port),$0
    )
})
}
    
open func killProcess(pid: UInt32, force: Bool)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeRustEngineError.lift) {
    uniffi_portkiller_ffi_fn_method_rustengine_kill_process(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(pid),
        FfiConverterBool.lower(force),$0
    )
})
}
    
open func refresh()throws  {try rustCallWithError(FfiConverterTypeRustEngineError.lift) {
    uniffi_portkiller_ffi_fn_method_rustengine_refresh(self.uniffiClonePointer(),$0
    )
}
}
    
open func reloadConfig()throws  {try rustCallWithError(FfiConverterTypeRustEngineError.lift) {
    uniffi_portkiller_ffi_fn_method_rustengine_reload_config(self.uniffiClonePointer(),$0
    )
}
}
    
open func removeFavorite(port: UInt16)throws  {try rustCallWithError(FfiConverterTypeRustEngineError.lift) {
    uniffi_portkiller_ffi_fn_method_rustengine_remove_favorite(self.uniffiClonePointer(),
        FfiConverterUInt16.lower(port),$0
    )
}
}
    
open func removeWatchedPort(port: UInt16)throws  {try rustCallWithError(FfiConverterTypeRustEngineError.lift) {
    uniffi_portkiller_ffi_fn_method_rustengine_remove_watched_port(self.uniffiClonePointer(),
        FfiConverterUInt16.lower(port),$0
    )
}
}
    
open func toggleFavorite(port: UInt16)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeRustEngineError.lift) {
    uniffi_portkiller_ffi_fn_method_rustengine_toggle_favorite(self.uniffiClonePointer(),
        FfiConverterUInt16.lower(port),$0
    )
})
}
    
open func toggleWatch(port: UInt16)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeRustEngineError.lift) {
    uniffi_portkiller_ffi_fn_method_rustengine_toggle_watch(self.uniffiClonePointer(),
        FfiConverterUInt16.lower(port),$0
    )
})
}
    
open func updateWatchedPort(port: UInt16, notifyOnStart: Bool, notifyOnStop: Bool)throws  {try rustCallWithError(FfiConverterTypeRustEngineError.lift) {
    uniffi_portkiller_ffi_fn_method_rustengine_update_watched_port(self.uniffiClonePointer(),
        FfiConverterUInt16.lower(port),
        FfiConverterBool.lower(notifyOnStart),
        FfiConverterBool.lower(notifyOnStop),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRustEngine: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = RustEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> RustEngine {
        return RustEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: RustEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RustEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: RustEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRustEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> RustEngine {
    return try FfiConverterTypeRustEngine.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRustEngine_lower(_ value: RustEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypeRustEngine.lower(value)
}


public struct RustNotification {
    public var notificationType: String
    public var port: UInt16
    public var processName: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(notificationType: String, port: UInt16, processName: String?) {
        self.notificationType = notificationType
        self.port = port
        self.processName = processName
    }
}



extension RustNotification: Equatable, Hashable {
    public static func ==(lhs: RustNotification, rhs: RustNotification) -> Bool {
        if lhs.notificationType != rhs.notificationType {
            return false
        }
        if lhs.port != rhs.port {
            return false
        }
        if lhs.processName != rhs.processName {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(notificationType)
        hasher.combine(port)
        hasher.combine(processName)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRustNotification: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RustNotification {
        return
            try RustNotification(
                notificationType: FfiConverterString.read(from: &buf), 
                port: FfiConverterUInt16.read(from: &buf), 
                processName: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: RustNotification, into buf: inout [UInt8]) {
        FfiConverterString.write(value.notificationType, into: &buf)
        FfiConverterUInt16.write(value.port, into: &buf)
        FfiConverterOptionString.write(value.processName, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRustNotification_lift(_ buf: RustBuffer) throws -> RustNotification {
    return try FfiConverterTypeRustNotification.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRustNotification_lower(_ value: RustNotification) -> RustBuffer {
    return FfiConverterTypeRustNotification.lower(value)
}


public struct RustPortInfo {
    public var id: String
    public var port: UInt16
    public var pid: UInt32
    public var processName: String
    public var address: String
    public var user: String
    public var command: String
    public var fd: String
    public var isActive: Bool
    public var processType: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, port: UInt16, pid: UInt32, processName: String, address: String, user: String, command: String, fd: String, isActive: Bool, processType: String) {
        self.id = id
        self.port = port
        self.pid = pid
        self.processName = processName
        self.address = address
        self.user = user
        self.command = command
        self.fd = fd
        self.isActive = isActive
        self.processType = processType
    }
}



extension RustPortInfo: Equatable, Hashable {
    public static func ==(lhs: RustPortInfo, rhs: RustPortInfo) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.port != rhs.port {
            return false
        }
        if lhs.pid != rhs.pid {
            return false
        }
        if lhs.processName != rhs.processName {
            return false
        }
        if lhs.address != rhs.address {
            return false
        }
        if lhs.user != rhs.user {
            return false
        }
        if lhs.command != rhs.command {
            return false
        }
        if lhs.fd != rhs.fd {
            return false
        }
        if lhs.isActive != rhs.isActive {
            return false
        }
        if lhs.processType != rhs.processType {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(port)
        hasher.combine(pid)
        hasher.combine(processName)
        hasher.combine(address)
        hasher.combine(user)
        hasher.combine(command)
        hasher.combine(fd)
        hasher.combine(isActive)
        hasher.combine(processType)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRustPortInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RustPortInfo {
        return
            try RustPortInfo(
                id: FfiConverterString.read(from: &buf), 
                port: FfiConverterUInt16.read(from: &buf), 
                pid: FfiConverterUInt32.read(from: &buf), 
                processName: FfiConverterString.read(from: &buf), 
                address: FfiConverterString.read(from: &buf), 
                user: FfiConverterString.read(from: &buf), 
                command: FfiConverterString.read(from: &buf), 
                fd: FfiConverterString.read(from: &buf), 
                isActive: FfiConverterBool.read(from: &buf), 
                processType: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: RustPortInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterUInt16.write(value.port, into: &buf)
        FfiConverterUInt32.write(value.pid, into: &buf)
        FfiConverterString.write(value.processName, into: &buf)
        FfiConverterString.write(value.address, into: &buf)
        FfiConverterString.write(value.user, into: &buf)
        FfiConverterString.write(value.command, into: &buf)
        FfiConverterString.write(value.fd, into: &buf)
        FfiConverterBool.write(value.isActive, into: &buf)
        FfiConverterString.write(value.processType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRustPortInfo_lift(_ buf: RustBuffer) throws -> RustPortInfo {
    return try FfiConverterTypeRustPortInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRustPortInfo_lower(_ value: RustPortInfo) -> RustBuffer {
    return FfiConverterTypeRustPortInfo.lower(value)
}


public struct RustWatchedPort {
    public var id: String
    public var port: UInt16
    public var notifyOnStart: Bool
    public var notifyOnStop: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, port: UInt16, notifyOnStart: Bool, notifyOnStop: Bool) {
        self.id = id
        self.port = port
        self.notifyOnStart = notifyOnStart
        self.notifyOnStop = notifyOnStop
    }
}



extension RustWatchedPort: Equatable, Hashable {
    public static func ==(lhs: RustWatchedPort, rhs: RustWatchedPort) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.port != rhs.port {
            return false
        }
        if lhs.notifyOnStart != rhs.notifyOnStart {
            return false
        }
        if lhs.notifyOnStop != rhs.notifyOnStop {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(port)
        hasher.combine(notifyOnStart)
        hasher.combine(notifyOnStop)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRustWatchedPort: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RustWatchedPort {
        return
            try RustWatchedPort(
                id: FfiConverterString.read(from: &buf), 
                port: FfiConverterUInt16.read(from: &buf), 
                notifyOnStart: FfiConverterBool.read(from: &buf), 
                notifyOnStop: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: RustWatchedPort, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterUInt16.write(value.port, into: &buf)
        FfiConverterBool.write(value.notifyOnStart, into: &buf)
        FfiConverterBool.write(value.notifyOnStop, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRustWatchedPort_lift(_ buf: RustBuffer) throws -> RustWatchedPort {
    return try FfiConverterTypeRustWatchedPort.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRustWatchedPort_lower(_ value: RustWatchedPort) -> RustBuffer {
    return FfiConverterTypeRustWatchedPort.lower(value)
}


public enum RustEngineError {

    
    
    case ScanFailed(message: String)
    
    case KillFailed(message: String)
    
    case PermissionDenied(message: String)
    
    case ConfigError(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRustEngineError: FfiConverterRustBuffer {
    typealias SwiftType = RustEngineError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RustEngineError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ScanFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .KillFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .PermissionDenied(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .ConfigError(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RustEngineError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .ScanFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .KillFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .PermissionDenied(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .ConfigError(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))

        
        }
    }
}


extension RustEngineError: Equatable, Hashable {}

extension RustEngineError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt16: FfiConverterRustBuffer {
    typealias SwiftType = [UInt16]

    public static func write(_ value: [UInt16], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt16.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt16] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt16]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt16.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRustNotification: FfiConverterRustBuffer {
    typealias SwiftType = [RustNotification]

    public static func write(_ value: [RustNotification], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRustNotification.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RustNotification] {
        let len: Int32 = try readInt(&buf)
        var seq = [RustNotification]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRustNotification.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRustPortInfo: FfiConverterRustBuffer {
    typealias SwiftType = [RustPortInfo]

    public static func write(_ value: [RustPortInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRustPortInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RustPortInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [RustPortInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRustPortInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRustWatchedPort: FfiConverterRustBuffer {
    typealias SwiftType = [RustWatchedPort]

    public static func write(_ value: [RustWatchedPort], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRustWatchedPort.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RustWatchedPort] {
        let len: Int32 = try readInt(&buf)
        var seq = [RustWatchedPort]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRustWatchedPort.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
nonisolated(unsafe) private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_portkiller_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_add_favorite() != 12088) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_add_watched_port() != 62351) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_get_favorites() != 39295) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_get_pending_notifications() != 35984) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_get_ports() != 57191) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_get_watched_ports() != 21591) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_has_pending_notifications() != 40219) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_is_favorite() != 42718) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_is_port_active() != 1835) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_is_process_running() != 24331) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_is_watched() != 27199) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_kill_port() != 30517) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_kill_process() != 40992) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_refresh() != 62873) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_reload_config() != 59240) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_remove_favorite() != 61235) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_remove_watched_port() != 20679) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_toggle_favorite() != 24554) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_toggle_watch() != 61784) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_method_rustengine_update_watched_port() != 61189) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_portkiller_ffi_checksum_constructor_rustengine_new() != 46607) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all