#!/bin/bash
set -e

# Setup Xcode project for PortKiller with Rust backend
# Usage: ./scripts/setup-xcode.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
RUST_LIB_DIR="$PROJECT_DIR/.build/rust/lib"

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║           Setting up Xcode for PortKiller                         ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""

# Check if Rust library exists
if [ ! -f "$RUST_LIB_DIR/libportkiller.a" ]; then
    echo "⚠️  Rust library not found. Building..."
    "$SCRIPT_DIR/build-rust.sh"
fi

echo "✓ Rust library found: $RUST_LIB_DIR/libportkiller.a"

# Create xcconfig file for Xcode
XCCONFIG="$PROJECT_DIR/PortKiller.xcconfig"
cat > "$XCCONFIG" << EOF
// Xcode configuration for PortKiller with Rust backend
// Generated by setup-xcode.sh

// Library search paths
LIBRARY_SEARCH_PATHS = \$(inherited) "$RUST_LIB_DIR"

// Link Rust library
OTHER_LDFLAGS = \$(inherited) -lportkiller
EOF

echo "✓ Created: $XCCONFIG"

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                      Setup Complete!                              ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "To open in Xcode:"
echo "  open Package.swift"
echo ""
echo "In Xcode, go to:"
echo "  1. Product → Scheme → Edit Scheme"
echo "  2. Build → Pre-actions → Add 'Run Script Action'"
echo "  3. Add: cd \"\$SRCROOT\" && ./scripts/build-rust.sh"
echo ""
echo "Or manually set in Build Settings:"
echo "  • Library Search Paths: $RUST_LIB_DIR"
echo "  • Other Linker Flags: -lportkiller"
